### ISSUE TITLE
Not working for youtube

### ISSUE THREAD

**Issue by RushabhJoshi** [essence/essence#102]
$e = new Essence\Essence;
$media = $e->extract('https://www.youtube.com/watch?v=HekceCwbSwY');

var_dump($media);

here media is _null_

**Comment by felixgirault** [comment]
This seems to happen because of the private status of the video.
It works well with this one from the same author for example : https://www.youtube.com/watch?v=WLF7t2yiUkY

**Comment by RushabhJoshi** [comment]
http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=WE3TVrfoOqk&format=json

this is working fine. 
I am not getting the point. if video is private why the above link giving me data. but not this library.

Thanks

**Comment by RushabhJoshi** [comment]
BTW
this video is not private, its unlisted

other unlisted videos like https://www.youtube.com/watch?v=KCaZ-AyXGlY and https://www.youtube.com/watch?v=-35jMRZVPJQ are working fine

**Comment by felixgirault** [comment]
That's what I meant by private, sorry :)

The first video you've given me is the only one not working with essence, but also the only one not working when calling the oembed endpoint directly : http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=HekceCwbSwY&format=json

There seems to be nothing wrong in the end.

**Comment by RushabhJoshi** [comment]
I am really really really sorry.

I accidentally replaced the video id so I got confused.

**Comment by felixgirault** [comment]
No problem :)
Cheers
