### ISSUE TITLE
Minimun PHP version

### ISSUE THREAD

**Issue by chonz0** [essence/essence#103]
Hi!

I was trying to install Essence in my MediaTemple Gridserver and found that the latest PHP version it offers is 5.5.something, while Essence requires >=5.6.0
Is Essence currently using features from 5.6.0+, or you've set that requirement just because it's the latest PHP stable release?
I've found that many other hosting providers are also missing PHP 5.6 support.

Best regards,
Gonzalo

**Comment by felixgirault** [comment]
Hi!

Yeah... I'm really sorry about that, it has already been reported by other users and I realize it is going to be a problem for many of you.
In fact, there is a dependency (Parkour) that requires PHP 5.6 for some of its functionalities, but these functionalities are not directly used in essence.
Parkour is a library that I'm maintaining, so I could add support for PHP 5.5, until 5.6 is more widely adopted.

I'll try to do it soon ;)

**Comment by chonz0** [comment]
Ah, nice to hear that :) yes, it's a shame that most hosting providers keep holding the developers back... So yes, maybe it would be a good idea to add support for 5.5 for the moment.
Thank you so much! ;)

**Comment by felixgirault** [comment]
Note that until I update the lib, you should be able to use it anyway, because as I said, essence is not using the PHP 5.6 functionalities of Parkour.
So theoretically, the problematic code should not be called, and thus not break. (I hope!)

Thank you for using essence anyway ;)

**Comment by mreiche** [comment]
So you trying to provide PHP 5.5 support in 3.1?

**Comment by felixgirault** [comment]
Yup :)

**Comment by felixgirault** [comment]
@chonz0 @mreiche I finally got some time to update essence. Version 3.1.0 now supports PHP 5.5 :) https://github.com/essence/essence/releases/tag/3.1.0

**Comment by chonz0** [comment]
You are awesome <3
Thank you very much, Felix!
