### ISSUE TITLE
Why PHP 5.6 dependency?

### ISSUE THREAD

**Issue by mreiche** [essence/essence#104]
I run an environment with PHP 5.5 from Ubuntu LTS and I cant install essence from composer, because it requires PHP 5.6 or higher. But why and is it possible to backport to PHP 5.5?

**Comment by felixgirault** [comment]
Hi,

I'm sorry about that, it is apparently a problem for many devs...
You can read my response here : https://github.com/essence/essence/issues/103

I didn't have the time to do the fix, but I'll do it as soon as I can.
