### ISSUE TITLE
Completer won't replace default props

### ISSUE THREAD

**Issue by zyuhel** [essence/essence#107]
If you use completer when in Media::setDefaults
$this->_properties += $properties;

won't allow to overwrite base properties (providerName,providerUrl,type, etc. ), 
it should be changed to 		$this->_properties = $properties+$this->_properties;
or we need to set some other field using completer and when overwrite using reindexer. IMO changing of properties order won't raise problem;

**Comment by zyuhel** [comment]
It seems that changing order breaks some tests. So may be there is other way to provide default values for this fields?

**Comment by zyuhel** [comment]
setDefaults could call setDefault instead of just adding arrays. Slower, but more accurate.

**Comment by felixgirault** [comment]
It seems fine and more coherent, thanks.
And with the kind of data that essence is handling, it shouldn't be any noticeably slower.
