### ISSUE TITLE
Class 'Parkour\Transform' not found in /var/www/html/essence/lib/Essence/Di/Container.php on line 76

### ISSUE THREAD

**Issue by Ananth103** [essence/essence#115]
```php
<?php 

spl_autoload_register(function($class) {
  $path = dirname( __FILE__ ).'/lib/'.str_replace('\\', '/', $class) . '.php';
  if (file_exists($path)) require $path;
});

require 'lib/Essence/Essence.php';

error_reporting(-1);
ini_set('display_errors', 'On');

$Essence = new Essence\Essence();
echo $Media = $Essence->extract('http://www.youtube.com/watch?v=39e3KYAmXK4');
?>
```

Gives Me,

```
Class 'Parkour\Transform' not found in /var/www/html/essence/lib/Essence/Di/Container.php on line 76
```

Where i am wrong? :(

**Comment by felixgirault** [comment]
Did you install only `essence/essence` ?
The package depends on some others that are listed in `composer.json` : https://github.com/essence/essence/blob/master/composer.json

I assume you are not using composer here, so you should also clone these dependencies and setup the appropriate autoloaders.

**Comment by Ananth103** [comment]
yes.you correct i missed composer now its work.But it doesnot crawl videos from blog sites. What it may be the issue.

Thanks.

**Comment by felixgirault** [comment]
Do you have an example with an URL that I could test ?

**Comment by Ananth103** [comment]
Sure. 

 1. http://www.bbc.com/news/video_and_audio/international
 2. http://www.dailymotion.com/in

**Comment by zyuhel** [comment]
For bbc there will be a sort of problems, because it hasn't got video urls on page, and is builded using js on client. There can be solution. But i don't think that it is issue in library. 
You have an error. Crawl method expects html not url. This works flawlessly. 
````
<?php
require 'vendor/autoload.php';

$Essence = new Essence\Essence();

$urls = $Essence->crawl(file_get_contents('http://www.dailymotion.com/in'));

error_reporting(-1);
ini_set('display_errors', 'On');

print_r($urls);
?>
````

**Comment by zyuhel** [comment]
You could also use crawlUrl method.  There was a little error in docs.

**Comment by Ananth103** [comment]
Please test this video url : http://edu.bmfrrp.com/static/resources/FullIQ-1.mp4

```php
<?php
require 'vendor/autoload.php';

$Essence = new Essence\Essence();
$Media = $Essence->extract('http://edu.bmfrrp.com/static/resources/FullIQ-1.mp4');

error_reporting(-1);
ini_set('display_errors', 'On');

print_r($Media);

if ($Media) {
    echo  "valid";
} else {
	echo  "invalid";
}
?>
```
The above video url is vaild once.but its give output "invalid";

**Comment by felixgirault** [comment]
At this time, essence is not able to get information from anything that is not a web page.
In your example, you're trying with a direct link to a video, which cannot be parsed.

We started a discussion (https://github.com/essence/essence/issues/112) with @zyuhel about how we could get minimal info from these kind of URLs, but it is not possible right now, sorry :)

**Comment by Ananth103** [comment]
Okay. Thank you :)
