### ISSUE TITLE
Support for proxys

### ISSUE THREAD

**Issue by mreiche** [essence/essence#118]
Please provide support for proxies withint Essence\Http\Client\Curl

http://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy

**Comment by felixgirault** [comment]
Hi,

You can already configure the client with cURL props, through the container :

```php
$Essence = new Essence\Essence([
	'Http' => Essence\Di\Container::unique(function() {
		return new Essence\Http\Client\Curl([
			// cURL props
		])
	})
]);
```
