### ISSUE TITLE
Cannot use 'Null' as class name as it is reserved - PHP7

### ISSUE THREAD

**Issue by jloguercio** [essence/essence#121]
In PHP7 it throw this error when you try to replace.

Regards

**Comment by felixgirault** [comment]
Hi,

Can you tell me which version of Essence you are using ?
Also, do you have more info associated with the error message, like a file and a line number ?

**Comment by jloguercio** [comment]
Hi, im using v2.5, but i updating essence to the last version (v3.2) and works like a charm

Thank you

**Comment by felixgirault** [comment]
Good news :)
