### ISSUE TITLE
Conflicting support for PHP 5.4 vs 7.0

### ISSUE THREAD

**Issue by ywarnier** [essence/essence#122]
Hi guys,

Tag v2.5.2 does not work on PHP 7.0 because the "Null" class conflicts with reserved keywords in PHP 7.0.
Tag 3.2.0 does not work on PHP 5.4 because of the use of "yield", which only appears since PHP 5.5.

One of our (Chamilo) team members applied a patch to your branch 2.0 to support PHP 7.0. Not sure this is something you're interested in, but it would be great for us if you could include it so we could benefit from our lib and not require our users to support PHP 5.5 to upgrade to our new version.

The solution is clean and seems to work well so far: https://github.com/jmontoyaa/essence/commits/jmontoyaa-patch-1

I know about end of life of PHP 5.4 and all that. We just have a relatively non-technical target of people installing our portal in schools and stuff.

**Comment by felixgirault** [comment]
Hi,

I have no problem with that, I think a library should support as much environments as possible ;)
Could you make a pull request with your patch on branch 2.0 ?

**Comment by felixgirault** [comment]
Thank you guys, I published [version 2.6.0](https://github.com/essence/essence/releases/tag/2.6.0) with your fix ;)

**Comment by ywarnier** [comment]
I'm not really into the lib packaging procedures, but is there a known reason why 2.6.0 doesn't appear on packagist.org? Do you have to declare something there manually?

**Comment by ywarnier** [comment]
Sorry, I found my own answer after formulating the question:
"your package will be automatically crawled periodically" from https://packagist.org/

**Comment by felixgirault** [comment]
Oops, in fact it won't work...
In version 2.x, there was an explicit version set in `package.json` (https://github.com/essence/essence/blob/2.0/composer.json#L5), and composer looks for this one first.
This was removed in 3.x so composer looks directly at git tags.
I'll remove that in 2.x and tag a version 2.6.1 to fix the problem.

**Comment by ywarnier** [comment]
:+1:

**Comment by felixgirault** [comment]
That's ok now :)

**Comment by ywarnier** [comment]
Excellent, tested and approved the whole cycle of including, composer updating on a PHP 5.4 and testing on PHP 7.0. This can be considered super-closed now!
