### ISSUE TITLE
Problem with soundcloud.com embed

### ISSUE THREAD

**Issue by gmclelland** [essence/essence#127]
Hello, thanks for sharing this wonderful library!

I recently ran into a problem with soundcloud.com.

$test = $this->essence->extract("https://soundcloud.com/thirdday/i-need-a-miracle-1");

It say's $test is NULL

However, if I try the following it works.  It returns data.

$test = $this->essence->extract("https://soundcloud.com/centricitymusic/jordan-feliz-the-river");

Any idea as to what is going on?

I'm running 3.2.0

**Comment by felixgirault** [comment]
Hi, 

I'm glad you find the lib useful :)

I tried a direct call to the SoundCloud API and it doesn't respond anything when using the first link, maybe there is an access restriction with this track ?

```sh
curl "http://soundcloud.com/oembed" -d 'format=json' -d 'url=https://soundcloud.com/thirdday/i-need-a-miracle-1'

# nothing
```

```sh
curl "http://soundcloud.com/oembed" -d 'format=json' -d 'url=https://soundcloud.com/centricitymusic/jordan-feliz-the-river'                                                                                                      

{"version":1.0,"type":"rich","provider_name":"SoundCloud","provider_url":"http://soundcloud.com","height":400,"width":"100%","title":"Jordan Feliz - The River by Centricity Music","description":"Listen to new artist Jordan Feliz's new song \"The River!\"","thumbnail_url":"http://i1.sndcdn.com/artworks-000122744895-hmhegg-t500x500.jpg","html":"\u003Ciframe width=\"100%\" height=\"400\" scrolling=\"no\" frameborder=\"no\" src=\"https://w.soundcloud.com/player/?visual=true\u0026url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F213878309\u0026show_artwork=true\"\u003E\u003C/iframe\u003E","author_name":"Centricity Music","author_url":"http://soundcloud.com/centricitymusic"}
```

(see https://developers.soundcloud.com/docs/oembed)

**Comment by gmclelland** [comment]
Hmm.. interesting.  Maybe there is an access restriction?....I guess so, strange.

Thanks for your help, I just wanted to make sure there wasn't something wrong with Essence.

FYI...Essence is being used in the https://github.com/felixwahner/TextformatterOEmbed module for the Processwire CMS at https://processwire.com.  Didn't know if you were aware of this module?  Just thought you might like to know how it is being used.

**Comment by felixgirault** [comment]
Nope, I wasn't aware of this module, thanks for letting me now :)
