### ISSUE TITLE
Extract from non-providers?

### ISSUE THREAD

**Issue by OxyFuse** [essence/essence#128]
> to extract media information from websites, like youtube videos, twitter statuses or **_blog articles_**.

I just want to clarify if this can extract information from non-providers such as blogs?

    $Media = $Essence->extract('https://maptia.com/daesung/stories/on-the-shores-of-a-vanishing-island');
    if ($Media) {
        echo $Media->title;
    } else {
        echo 'nothing';
    }

 I have tried:

* https://maptia.com/daesung/stories/on-the-shores-of-a-vanishing-island
* http://www.bbc.com/future/story/20161125-the-worms-that-cost-20000-a-kilo
* http://www.marvelous-homes.com/top-10-most-beautiful-forest-house/
* https://aeon.co/essays/how-domestication-changes-species-including-the-human
* http://listverse.com/2013/08/11/10-ridiculously-slow-to-bloom-plants/
* http://mentalfloss.com/article/26483/4-bizarre-experiments-should-never-be-repeated

but it results to "nothing"

**Comment by felixgirault** [comment]
Hi,

From what I see, it should work correctly as there is TwitterCards and/or OpenGraph info in those pages.

It seems that, by default, Essence won't try to extract resources from URLs it doesn't recognize.
I thought there was a bit of doc on how to let it extract anything but it seems there is none...

What version of Essence are you using ?
Depending on your version, I will tell you what to do ;)

**Comment by OxyFuse** [comment]
Thanks for the response.

I just downloaded the master branch and create an autoloader since I didn't use composer.

**Comment by felixgirault** [comment]
I think you can get it to work if you initialize Essence like this:

```php
$Essence = new Essence\Essence([
	'filters' => [
		'OEmbedProvider' => '~.+~',
		'OpenGraphProvider' => '~.+~',
		'TwitterCardsProvider' => '~.+~'
	]
]);
```

(I don't have time to effectively test this right now but it should be ok)
Basically, this registers fallback providers that will try to extract info from any URL.

**Comment by OxyFuse** [comment]
Here's what I've found when testing the code:

* If the first provider failed, it won't proceed checking with the other two providers. That is, if the URL has no oEmbed data but has an Open Graph or Twitter Cars data, it will still results to "nothing".

* Getting a blank result but not "nothing", i.e. http://www.marvelous-homes.com/top-10-most-beautiful-forest-house/ has blank result even though it has oEmbed data. Or if change the first provider as OpenGraphProvider, then https://aeon.co/essays/how-domestication-changes-species-including-the-human  is blank even if it has some Open Graph data. Means (`if ($Media)` is becoming TRUE but can't get the information requested.

* While http://www.bbc.com/future/story/20161125-the-worms-that-cost-20000-a-kilo has only an Open Graph data, it will still show result even if the first provider is OEmbedProvider (_this is contradicting to point 1 above_).

**Comment by joshuabaker** [comment]
@felixgirault, we’re trying to get this working too and have encountered similar issues. The solution you’ve provided does seem to work on some URLs but not others.

Might you be able to help document the correct approach a bit more?

**Comment by felixgirault** [comment]
@joshuabaker Hi, 
I think the main problem here is that essence stops at the first provider which matches an URL and does not fail to retrieve something.
So if OEmbed returns an empty result for whatever reason, it is considered a success and the other providers will not be executed.

Maybe the better way to solve this would be to add an option, when extracting data, to allow each provider to be executed on top of each other, so it would not stop at the first one. This would also solve the issue https://github.com/essence/essence/issues/131, 

The only problem is : I'm in vacations right now, and I don't have much time to work on it :)

If anyone of you wants to fiddle with the code and make a pull request, the only place where to add code would be here https://github.com/essence/essence/blob/master/lib/Essence/Extractor.php#L48

This loops over potential providers, and you can see on this line that it returns the first result available https://github.com/essence/essence/blob/master/lib/Essence/Extractor.php#L53

The trick would be to add an option that can change this behavior.

**Comment by scottybo** [comment]
Any news on this? Still seems to be an issue

**Comment by felixgirault** [comment]
Hi, 

Indeed this should still be a problem as I didn't have time to work on it then.
And to be honest I totally forgot about that since then :)

I'll try to test something today, since this shouldn't be too long to implement.

To solve this problem, and the one from https://github.com/essence/essence/issues/131, I think I'll add an option to switch between:
* the current behavior
* a mode where essence tries the next available provider when one fails
* a mode where it calls all the available providers and merge the results

**Comment by felixgirault** [comment]
I tried to implement something, but as I was testing out the current behavior, I didn't encounter the same issue (using the configuration I suggested in https://github.com/essence/essence/issues/128#issuecomment-297428187). 

Also, some of the URLs provided in here are not available anymore, so maybe there is still an issue but I just didn't see it.

Do you have any problematic URLs to give me so that I could test real failing cases ? @OxyFuse @joshuabaker @scottybo

**Comment by scottybo** [comment]
@felixgirault sorry - I ended up using the embed/embed package so don't have any info that can help at this point

**Comment by felixgirault** [comment]
I'm closing the issue, since no one seems to be concerned anymore.
Don't hesitate to reopen if needed ;)
