### ISSUE TITLE
Imgur provider needs to be fixed

### ISSUE THREAD

**Issue by unnikked** [essence/essence#134]
If you pass an imgur link you get `null`. 

From the imgur provide I can see that the request is formatted like this: 

```
http://api.imgur.com/oembed?format=json&url=qtQYdZI
```

You will get: 

```json
{
  "data": {
    "error": "HTTP Access is disabled. Requests must use SSL (HTTPS)."
  },
  "success": false,
  "status": 400
}
```

But if you use: 

```
https://api.imgur.com/oembed?format=json&url=qtQYdZI
```

You will get the right information: 

```json
{
  "version": "1.0",
  "type": "rich",
  "provider_name": "Imgur",
  "provider_url": "https:\/\/imgur.com",
  "width": 540,
  "height": 500,
  "html": "<blockquote class=\"imgur-embed-pub\" lang=\"en\" data-id=\"qtQYdZI\"><a href=\"https:\/\/imgur.com\/qtQYdZI\">The best boy<\/a><\/blockquote><script async src=\"\/\/s.imgur.com\/min\/embed.js\" charset=\"utf-8\"><\/script>"
}
```

Please fix this as I can't make a PR at this time.

**Comment by TheLuckyOne** [comment]
#135

**Comment by felixgirault** [comment]
I'm closing this issue as the pull request fixed it.
Thanks @unnikked @TheLuckyOne

**Comment by yvettep321** [comment]
curl -H "Accept-Version: 3" https:


what do put after https:?
somehow someone had put something else which is not right I'm sure it's not right I'll give you an example of Iwhat was on my computer curl -H "Accept-Version: 3" "https://lookup.binlist.net/45717360"

**Comment by yvettep321** [comment]
thank you

**Comment by felixgirault** [comment]
Hi,
I'm sorry I don't understand what you want to do.
Could you explain a little more what you're trying to achieve?
