### ISSUE TITLE
Add referrer to Curl for Vimeo private videos

### ISSUE THREAD

**Issue by wordragon** [essence/essence#151]
Is there a simple way to add CURL_REFERER (sic) option to the Http object?  Vimeo requires this to get all info from a private video.  Without it, you can't get a thumbnail, for example.

**Comment by felixgirault** [comment]
Hi,
you should be able to do this by customizing the default HTTP client, upon instanciation:

```php
$essence = new Essence\Essence([
	Essence\Di\Container::unique(function($container) {
		$http = new Essence\Http\Client\Curl([
			CURL_REFERER => 'referrer'
		]);

		$http ->setUserAgent(
			$container->get('httpUserAgent')
		);

		return $http;
	})
]);
```

I didn't try this code but it should be ok. 
I've assembled it from:
* [The default configuration of the client](https://github.com/essence/essence/blob/master/lib/Essence/Di/Container/Standard.php#L62)
* [The constructor parameters of the client](https://github.com/essence/http/blob/master/src/Client/Curl.php#L46)

**Comment by wordragon** [comment]
Thanks, Félix.  That works.  Just what I was looking for!  You need to specify 'Http'=> in the configuration array, though.
