### ISSUE TITLE
Problem when embedding an instagram video

### ISSUE THREAD

**Issue by gustavomanolo** [essence/essence#57]
When i try to get the embed code of http://instagram.com/p/muPi-dqMnh the script retrieves an "img" tag with an mp4 code inside which is incorrect, i think that for videos on instagram i should get an "iframe" with type of "video" not "photo".

**Comment by felixgirault** [comment]
I tried to extract info from your URL again with the master version and the HTML is fine.
It seems like Instagram fixed their code.
I'm closing the issue, don't hesitate to reopen it if you find something wrong ;)
