### ISSUE TITLE
Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by fabienlege** [essence/essence#71]
Hello, i don't understant why i have this error when i launch a page who use Esscence i have this error : 
```
Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in in /var/www/html/elab/vendor/fg/essence/lib/Essence/Http/Client/Curl.php line 60
```
with my symfony 2.3 project.

This error occur at this line of my controller

```
$manager = \Essence\Essence::instance();
```
Thank's

**Comment by NerxhanMusliu** [comment]
Hello, 

I made your changes, but still get the error.
<code>Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in in /var/www/httpdocs/local/vendor/essence/essence/lib/Essence/Http/Client/Curl.php line: 52</code>

Thanks

**Comment by NerxhanMusliu** [comment]
I solved my problem,

It was a php version bug with open_basedir https://bugs.php.net/bug.php?id=65646.

I updated to php 5.6 and everthing works fine.

**Comment by felixgirault** [comment]
Ok great :)
