### ISSUE TITLE
Text fields - multiline issue

### ISSUE THREAD

**Issue by diurpaneus** [essence/essence#91]
In Text fields components there is a limitation of 50 characters per row.

**Comment by felixgirault** [comment]
Hi, 

You probably wanted to comment on this repo https://github.com/PearlVentures/Essence.
Also, don't hesitate to describe your problem a little more, and a "Hello" wouldn't hurt!

**Comment by diurpaneus** [comment]
Hello,
Sorry...I'm new to this :)

**Comment by felixgirault** [comment]
No problem, welcome aboard ;)
