### ISSUE TITLE
Switching to v3: failed to load

### ISSUE THREAD

**Issue by distantnative** [essence/essence#94]
I'm just trying to move to the new version of Essence - I'm not using composer and so I'm trying to implement it manually, but I get the following error:

```
Fatal error: Class 'Essence\Di\Container\Standard' not found in …/lib/Essence/Essence.php on line 70
```

after loading it via 

```php
require 'lib/Essence/Essence.php';
```

I'd appreciate any help or hints, how to load Essence completely (can't find any autoloader/bootstrap anymore).

**Comment by felixgirault** [comment]
Hi,

it seems like you will have to implement your own autoloader (http://php.net/manual/fr/function.spl-autoload-register.php).

I didn't do anything like that for some time but it would probably look like this:

```php
spl_autoload_register(function($class) {
    $path = '/path/to/essence/lib/' . str_replace('\\', '/', $class) . '.php';

    if (file_exists($path)) {
        require $path;
    }
});
```

Then you could just require Essence classes with `use`:

```php
use Essence\Essence;

new Essence();
```

I can't test that right now but tell me if you need more information ;)

**Comment by distantnative** [comment]
Thanks already!

Getting closer, but now I get the error:

```
Fatal error: Class 'Essence\Http\Client\Curl' not found in …/lib/Essence/Di/Container/Standard.php on line 66
```

And looking at the code, I can't actually find the class `Essence\Http\Client\Curl`:/

**Comment by felixgirault** [comment]
I did split the repo in 3 separate ones a few days ago. There is now the main one, Essence, and two other ones that handle DOM operations and HTTP requests (https://github.com/essence).

So you would have to clone those repos, and add a bit of code to autoload the classes they provide.

The code structure beeing a little different, the autoloader should look somethink like that:

```
spl_autoload_register(function($class) {
    if (strpos('Essence\\Http\\', $class)) {
        return;
    }

    // as the folder structure doesn't reflect the full namespace
    // we need to strip it from the class name
    $class = str_replace('Essence\\Http\\', '');
    $path = '/path/to/essence-http/src/' . str_replace('\\', '/', $class) . '.php';

    if (file_exists($path)) {
        require $path;
    }
});
```

And you would have to do the same thing for essence-dom. Again, this is not tested but it gives the idea :)

**Comment by distantnative** [comment]
Ahh, didn't see the separate repos. To share with others how it worked:

```
spl_autoload_register(function($class) {
  $path = dirname( __FILE__ ) . DS . 'lib' . DS . str_replace('\\', '/', $class) . '.php';
  if (file_exists($path)) require $path;
});
```

And I just copied the http and dom repo files to `lib/Essence/Http/` and `lib/Essence/Dom/` (my main file is located in the same directory as the `lib` folder).

Now the only error remaining is

```
Catchable fatal error: Argument 1 passed to Essence\Provider\Collection::configure() must be of the type array, string given, called in …/lib/Essence/Provider/Collection.php on line 84 and defined in …/lib/Essence/Mixin/Configurable.php on line 163
```

But I think that is related to the location of the `providers.php` which seems to be wrong atm. I will try to figure out its right place. Thanks!

**Comment by felixgirault** [comment]
Thanks for sharing!
I hope everything will work as expected now ;)
