### ISSUE TITLE
Unexpected T_USE

### ISSUE THREAD

**Issue by distantnative** [essence/essence#95]
I get the following error message:

> Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in …/lib/Essence/Di/Container.php on line 22

Any idea? Are you requiring a rather high PHP version?

**Comment by felixgirault** [comment]
Are you using the master version ?
It would be rather strange considering it is this line : https://github.com/essence/essence/blob/master/lib/Essence/Di/Container/Standard.php#L22

Essence is tested against PHP 5.5 to 7.0.

**Comment by distantnative** [comment]
I was running 5.3 - it just wasn't supported, sorry. But thanks again! ;)
