### ISSUE TITLE
Fatal error: Call to a member function getElementsByTagName() 

### ISSUE THREAD

**Issue by fiveDust** [essence/essence#96]
strict bool check fails in 

in Native.php

    protected function _document( $html ) {
    ...
    if ( $Document === false ) {

DomDocument::loadHtml()'s doc states 
@return bool true on success or false on failure. If called statically, returns a
     * DOMDocument and issues E_STRICT

but for some cases it returns null. ( PHP 5.4.41 Linux Debian )

FIX:
     if ( $Document === false || $Document === null ) {

or 

    if( $Document == null )

**Comment by felixgirault** [comment]
This should be OK now, I tagged a version 2.5.2 with the fix.
Thank you!

**Comment by fiveDust** [comment]
Thanks Felix!
