### ISSUE TITLE
No stable 3.x release

### ISSUE THREAD

**Issue by mreiche** [essence/essence#97]
Its confusing that the stable release of Essence is still 2.x, but the official documentation references to dev-master which is 3.x. So is the composer release (https://packagist.org/packages/essence/essence)

Please release 3.x or link to 2.x documentation. Many devs wont switch to dev-master.

**Comment by felixgirault** [comment]
I'm sorry about that, I'm aware that it could cause some trouble.
In fact I thought I would have released the 3.0 by now, but I keep updating things.

However, there is a short notice on top of the README stating that it is not version 2.0, and many other projects seem to operate the same way, having the latest developments on master.

I'll try to realease a 3.0 soon, or I'll switch to 2.0 as the default branch.

**Comment by mreiche** [comment]
Hi Felix. I think its absolutely no problem to make a early 3.0 release when your new API is stable.

**Comment by felixgirault** [comment]
I agree, but I'm still not so sure about some parts of the API :)

**Comment by felixgirault** [comment]
Version 3.0 is finally here :) https://github.com/essence/essence/releases/tag/3.0.0

**Comment by mreiche** [comment]
Thanks. I will try it out asap ;)
