### ISSUE TITLE
[Request] Support for "maxresdefault" for YouTube videos

### ISSUE THREAD

**Issue by chonz0** [essence/essence#98]
Any chance to have support for this high resolution image? (e.g.: http://i.ytimg.com/vi/lDi9uFcD7XI/maxresdefault.jpg)

BTW, loving Essence so far ;-) amazing work!

Best regards,
Gonzalo

**Comment by felixgirault** [comment]
Thank you :)

Yup! With version 2.0:

```
$Essence = Essence::instance();
$Essence->embed('url', [
    'thumbnailFormat' => 'max'
]);
```

With upcoming version 3.0 (master):

```
$Essence = new Essence([
    'youtubeThumbnailFormat' => 'max'
]);

$Essence->embed('url');
```

Note that there might be no max res image and there is currently no fallback, so use at your own risk ;)

**Comment by chonz0** [comment]
Wow that's great! I am currently using version 3.0, so I'll follow your advice and let you know, thank you very much ;-)

--- Enviado desde mi móvil.

**Comment by felixgirault** [comment]
I made a small mistake in the code examples above, if you are using version 3.0, you should write `$Essence->extract('url')`, not `$Essence->embed('url')` ;)

**Comment by chonz0** [comment]
Thanks! I'll check it out as soon as I can :)

According to http://stackoverflow.com/a/11387173 the 'maxresdefault' thumbnail is only available to 720p+ videos, so I guess I could be posible to look at the video height in order to decide if the 'maxresdefault' attribute would be available or not (although I think this isn't bulletproof)

**Comment by felixgirault** [comment]
Interesting, thank you!
I'll open an issue to remember that for version 3.1.

**Comment by chonz0** [comment]
Great! I think you can close this issue then (I didn't do it in case you wanted to keep it open, IDK)
Cheers!

**Comment by felixgirault** [comment]
Yep, cheers!
